name: Contexto Action
on: 
  push:
    branches:
      - main
      - 'aprendiendo-**'
jobs:
  CorriendoScript:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Correr script
        run: echo Desplegado en la rama $GITHUB_REF
  Contexto-env:
    runs-on: ubuntu-latest
    steps:
      - name: echo env
        run: echo "${{ env.var1 }} ${{ env.var2}} ${{ env.var3}}"
