name: Triggers Tarea
on:
  issues: #El tipo de trigger: issues
    types: #Los estados que activarán el trigger
    - [opened, edited, closed]
      
jobs:
  MiTareaNueva:
    runs-on: ubuntu-latest

    steps:
    - name: Clonando Repositorio
      uses: actions/checkout@v3
    - name: Instalando Node JS
      uses: actions/setup-node@v4
    - name: Imprimiendo Hola Mundo
      run: node index.js

