name: Triggers Tarea
on:
  workflow_dispatch:
    inputs:
      alerta: 
        description: 'Nivel'
        required: true
        default: medio
        type: choice
        options:
          - bajo
          - medio
          - alto
      tags:
        description: 'Opcional'
        required: true
        type: string
      
jobs:
  MiTareaNueva:
    runs-on: ubuntu-latest

    steps:
    - name: Clonando Repositorio
      uses: actions/checkout@v3
    - name: Instalando Node JS
      uses: actions/setup-node@v4
    - name: Imprimiendo Hola Mundo
      run: node index.js

