name: VariablesActions
on: 
  push:
    branches:
      - main 
env:
  DIA_DE_LA_SEMANA: "Lunes"
jobs:
  ProbandoActions:
    runs-on: ubuntu-latest
    env: 
      SALUDO: "HOLA"
    steps:
      - name: Correr Script YOLO
        run: |
            echo $SALUDO Mundo, $SALUDO_DOS, HOY ES $DIA_DE_LA_SEMANA .
            echo "$SALUDO Mundo, $SALUDO_DOS, HOY ES $DIA_DE_LA_SEMANA" .
        env: 
          SALUDO_DOS: "BUEN DÍA"
